feat: implementing mass assignment vulnerability
NeuraLegion/brokencrystals pull request #145
Opened 2021-11-14 18:02 UTC by Kif-Fando

Adding endpoint with Mass Assignment vulnerability.

2021-11-15 08:07 UTC, derevnjuk requested changes

2021-11-15 08:07 UTC, derevnjuk commented on src/users/users.controller.ts
> +      const newInfo = body;
Local variable is redundant here

2021-11-15 08:07 UTC, derevnjuk commented on src/users/users.service.ts
> +      throw new Error('Could not find user');
Why don't raise 404 HTTP exception in this case?

2021-11-15 08:30 UTC, Kif-Fando commented on src/users/users.service.ts
> +      [LDAP: error code 1 - 000004DC: Lda pErr: DSID-0C0906DC, comment: context not found., data 0, v1db1 ];
Tell it to prettier, it doesn`t like these spaces ;)

2021-11-15 08:30 UTC, Kif-Fando commented on src/users/users.controller.ts
> +    @Body() body: User,
My fault, fixed

2021-11-16 07:01 UTC, derevnjuk approved these changes

2021-11-16 07:01 UTC, merged