Feat(css injection): Add page with CSS Injection vulnerability
NeuraLegion/brokencrystals pull request #242
Opened 2023-02-03 17:16 UTC by tamirGer

I added a functionality that allows a user to pass a color that will be applied to the CSS rules of the Broken Crystals logo on the sign in page, e.g. `http://tamir-vm.lan:3001/userlogin?logobgcolor=transparent`. The code is not sanitized and thus passing a 'color' like this `http://tamir-vm.lan:3001/userlogin?logobgcolor=red;width:15px;` will apply additional rules to the CSS stylesheet.

2023-02-10 11:58 UTC, tamirGer commented
Hi @derevnjuk, please review :)

2023-02-11 08:39 UTC, derevnjuk requested changes

2023-02-11 08:39 UTC, derevnjuk commented on public/src/pages/auth/Login/Login.tsx
> +    return undefined;
Just use the `URL` class to parse the query parameters

```suggestion
    const { searchParams } = new URL(window.location.href);
    
    return searchParams.get('logobgcolor');
```

2023-02-11 08:40 UTC, derevnjuk commented
@tamirGer please adjust the PR title and body according to the comment at https://github.com/NeuraLegion/brokencrystals/pull/244#issuecomment-1426659521

2023-02-11 11:54 UTC, derevnjuk approved these changes

2023-02-11 11:54 UTC, merged