feat(bfla): add option to delete user profile picture with poor admin validation
NeuraLegion/brokencrystals pull request #269
Opened 2023-07-08 19:22 UTC by tamirGer

Adds endpoint DELETE `/users/one/:id/photo?isAdmin=` which allows to delete a user profile picture by the user ID. The `isAdmin` field is not validated on server side, thus it's possible to set it to true, and via ID enumeration delete any user's profile picture.

2023-07-10 14:12 UTC, anton7c3 submitted a review, later dismissed

2023-07-10 14:12 UTC, anton7c3 commented
I'd ask @derevnjuk to have a look, since this PR is not so trivial to me.

2023-07-13 07:12 UTC, derevnjuk requested changes

2023-07-13 07:12 UTC, derevnjuk commented on src/users/users.controller.ts
> +      return;
```suggestion
      await this.usersService.deletePhoto(id);
```

2023-07-13 07:12 UTC, derevnjuk commented on src/users/users.controller.ts
> +    }
Please remove the try/catch block as it will suppress the original error raised from the `deletePhoto` method, such as a `NotFoundError`.

2023-07-13 07:12 UTC, derevnjuk commented on src/users/users.controller.ts
> +    }
The redundant check, please remove

2023-07-17 05:47 UTC, derevnjuk approved these changes

2023-07-17 05:47 UTC, merged