feat(ui): add basic form authentication
NeuraLegion/brokencrystals pull request #31
Opened 2021-04-15 14:41 UTC by BMNTeam

closes #30

- change headers for HTML Based form request;
- add request type (op) to Login interface;

2021-04-19 09:14 UTC, derevnjuk requested changes

2021-04-19 09:14 UTC, derevnjuk commented on public/src/interfaces/User.ts
> +  APPLICATION_JSON = 'application/json'
Use a more abstract way to reflect auth type, especially when you have `FormMode`
e.g.

```ts
export enum AuthType {
  FORM = 'form',
  // OIDC, NTLM, etc
}
```

2021-04-21 13:36 UTC, derevnjuk commented
@BMNTeam please resolve conflicts

2021-04-21 14:55 UTC, BMNTeam commented
Closed as it's already implemented via https://github.com/NeuraLegion/brokencrystals/pull/36

2021-04-21 14:55 UTC, closed without merging