feat: Add API schema links
NeuraLegion/brokencrystals pull request #59
Opened 2021-06-22 09:53 UTC by tamirGer

2021-06-24 08:16 UTC, derevnjuk requested changes

2021-06-24 08:16 UTC, derevnjuk commented on public/src/pages/main/Header/Nav.tsx
> +                Schema Editor
```suggestion
                API Reference
```

2021-06-28 08:59 UTC, derevnjuk approved these changes

2021-07-12 12:27 UTC, derevnjuk reviewed
@tamirGer the main task implies refactoring API scheme itself. As we discussed, you should go through endpoints and adjust Swagger decorators to omit such declarations as Buffer, Readable, etc

See https://docs.nestjs.com/openapi/types-and-parameters#raw-definitions

2021-07-13 15:35 UTC, tamirGer commented
@derevnjuk This PR is not related to #63, this is additional functionality requested by @ArtLinkov. This should just allow easier access to the SWAGGER.

2021-07-13 15:37 UTC, derevnjuk commented
@tamirGer well, then you have to open a Github issue with some description and lint it to this PR

2021-07-13 16:43 UTC, tamirGer commented
@derevnjuk done

2021-07-13 19:13 UTC, merged